name: Build and Release ExcellentEnchants

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Manuel çalıştırma desteği

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository'yi Checkout Et
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 21 Kurulumu
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # 3. Maven ile Projeyi Derle
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      # 4. Derlenen JAR'ları Bul ve Yükle
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: excellent-enchants-jar
          path: '**/target/*.jar'
